spring:
  application:
    name: ServeNow
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ServeNow?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: manuFam2__8
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  
  # SQL Initialization
  sql:
    init:
      mode: always
      continue-on-error: false
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# JWT Configuration
jwt:
  secret: ServeNowSecretKeyForJWTTokenGeneration2024!@#$%^&*
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    try-it-out-enabled: true
    display-request-duration: true
    display-operation-id: false
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    filter: true
    show-extensions: true
    show-common-extensions: true
    deep-linking: true
    show-tags: true
    tags-sorter: alpha
    supported-submit-methods: ["get", "post", "put", "delete", "patch"]
    custom-html: /swagger-ui-custom.html
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  remove-broken-reference-definitions: true
  disable-swagger-defaults: true

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.manvanth.servenow: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE